language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
before_script:
  - sudo apt-get install astyle
script: ant test
notifications:
  irc: "irc.espner.net#noahsmod"
    template:
      - "Travis Auto Build Complete!"
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
